### ISSUE TITLE
Could not locate i18n config.

### ISSUE THREAD

**Issue by volfcan** [amannn/next-intl#1309]
### Description

after #1308 getting the following error on development:

`
⚠ Invalid next.config.js options detected:
 ⚠     Expected string, received boolean at "env.FEATURE_SEARCH_ENABLED"
 ⚠     "env._next_intl_trailing_slash" is missing, expected string
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
Error:

Could not locate i18n config. Create one at `./(src/)i18n.{js,jsx,ts,tsx}` or specify a custom location:

const withNextIntl = require('next-intl/plugin')(
  './path/to/i18n.tsx'
);

module.exports = withNextIntl({
  // Other Next.js configuration ...
});

    at resolveI18nPath (/Users/volfcan/ZedProjects/medusa-tutorial-frontend/node_modules/next-intl/dist/development/plugin.js:34:11)
    at Object.webpack (/Users/volfcan/ZedProjects/medusa-tutorial-frontend/node_modules/next-intl/dist/development/plugin.js:69:96)
    at getBaseWebpackConfig (/Users/volfcan/ZedProjects/medusa-tutorial-frontend/node_modules/next/dist/build/webpack-config.js:1738:32)
    at async Promise.all (index 1)
    at async Span.traceAsyncFn (/Users/volfcan/ZedProjects/medusa-tutorial-frontend/node_modules/next/dist/trace/trace.js:147:20)
    at async Span.traceAsyncFn (/Users/volfcan/ZedProjects/medusa-tutorial-frontend/node_modules/next/dist/trace/trace.js:147:20)
    at async HotReloader.start (/Users/volfcan/ZedProjects/medusa-tutorial-frontend/node_modules/next/dist/server/dev/hot-reloader-webpack.js:596:37)
    at async startWatcher (/Users/volfcan/ZedProjects/medusa-tutorial-frontend/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:1197:5)
    at async setupDevBundler (/Users/volfcan/ZedProjects/medusa-tutorial-frontend/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:1812:20)
    at async Span.traceAsyncFn (/Users/volfcan/ZedProjects/medusa-tutorial-frontend/node_modules/next/dist/trace/trace.js:147:20)

I don't know if this is related to #1308 or next.js specific error.

### Verifications

- [X] I've verified that the problem I'm experiencing isn't covered in [the docs](https://next-intl-docs.vercel.app/).
- [X] I've searched for similar, existing issues on GitHub and [Stack Overflow](https://stackoverflow.com/search?q=next-intl).
- [X] I've compared my app to [a working example](https://next-intl-docs.vercel.app/examples) to look for differences.

### Mandatory reproduction URL

https://github.com/volfcan/medusa-frontend

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

no errors

**Comment by amannn** [comment]
You can fix this error by upgrading `next-intl` to the latest version, built-in support for `./src/i18n/request.ts` was only added [very recently](https://github.com/amannn/next-intl/releases/tag/v3.19.0). Additionally, you might want to consider upgrading `next`, that helped me to get rid of another warning in your setup.

**Comment by volfcan** [comment]
fixed this but couldn't remember the solution. thanks for your time anyway 🙋🏼‍♂️

**Comment by salahbm** [comment]
@volfcan  Hey, could you remember the solution?

**Comment by Clago** [comment]
> @volfcan Hey, could you remember the solution?

[https://nextjs.org/docs/app/api-reference/next-config-js/env](url)
`
module.exports = {
  env: {
    customKey: 'my-value',
  },
}
`

**Comment by lockhaicttv** [comment]
Anyone here please help me solution, I configure my project exactly like the example repository with next 15 and next-int 4.0.2. But I still get the response when I remove i18n.ts, althought example project don't have this file

[Error: [next-intl] Could not find i18n config at ./i18n.ts, please provide a valid path.]

**Comment by uraden** [comment]
@lockhaicttv were you able to fix it?

**Comment by corbin-c** [comment]
@uraden @lockhaicttv I was able to solve the issue by pointing `createNextIntlPlugin` to the exact relative path to `requests.ts`. next-intl by default expects an `src` folder, so if your project does not have one, it will fail with the aforementioned error.

My minimal working `next.config.ts` file:

```typescript
import { NextConfig } from 'next'
import createNextIntlPlugin from 'next-intl/plugin'

const nextConfig = {}

const withNextIntl = createNextIntlPlugin('./i18n/request.ts')
export default withNextIntl(nextConfig)
``` 

hope this helps!
