### ISSUE TITLE
Unable to use next-intl with parallel routes (from App router)

### ISSUE THREAD

**Issue by dtrucs** [amannn/next-intl#255]
### Description

Hello,
Thank you for this great package!

I tried to combine the starter template you provide https://github.com/amannn/next-intl/tree/main/packages/example-next-13
with parallel routes and it doesn't work like expected.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/determined-pine-w8hx5w

### Reproduction description

Procedure for reproducing the problem :
1. Open the reproduction
2. Click on "Open modal" link.
3. The location URL changes, but not the content (which is normal here, I'll talk about it later)
4. At this point, If I refresh the nav, an error occurs.

Another use case:
1. Go to `/app/[locale]/layout.tsx` and uncomment `{/* modal */}` line 41 (to satisfy 3/ of the test case above)
2. Launch the app
3. Nothing works properly 

### Expected behaviour

Using parallel routes with i18n

**Comment by amannn** [comment]
Hey @dtrucs and thanks for the report! Does your example work without `next-intl`?

I also tried out parallel routes in one of the examples in this repository and got really strange errors that look more like general Next.js bugs to me (or maybe I don't understand parallel routes properly yet).

**Comment by sebpalluel** [comment]
I'm using `next-intl` with parallel and intercepting route without issue on my project.
From what i see in your project, the issue is with your implementation of the parallel routes and intercepting route. It's quite confusing but you need to provide a `default.js` in your parallel route for it to work.

**Comment by ReesMorris** [comment]
I think it might be more an issue with Next's support for parallel routes; my understanding is you can't use `(.)[dynamic]` currently ([issue here](https://github.com/vercel/next.js/issues/48143)). Since this library (and even Next's docs on adding intl) requires a top-level dynamic `[locale]` path, parallel routes doesn't work.

If you add the parallel route inside the `[locale]` directory, Next _does_ perform the route interception, but it replaces the whole layout which defeats the point.

The less-than-ideal workaround I'm using is to add the parallel routes into the `app` directory and duplicate them for every language, eg. _src/app/@authModal/(.)en/login/page.tsx_ (using `(.)en` instead of `(.)[locale]`). My app only has a limited number of locales so it's currently manageable, but hopefully they'll add support for that soon.

**Comment by desiboli** [comment]
Any solution or workaround to this yet ? 🙏

**Comment by amannn** [comment]
https://github.com/vercel/next.js/pull/51526 was merged, but not released yet in a stable version AFAIK. Once it is, it would be helpful if someone could confirm that this fixes this issue discussed in this thread. My impression is that there's nothing that `next-intl` needs to handle in regard to parallel/intercepted routes.

**Comment by desiboli** [comment]
I'm afraid this still isn't working after upgrading to Next.js 13.4.8...

**Comment by amannn** [comment]
Hmm, that's unfortunate. I guess if you remove `next-intl` from the reproduction (but keep `[locale]`), the Next.js team might be thankful for a bug report.

**Comment by ReesMorris** [comment]
I have had a bit more success with `next@13.4.8` and `next-intl@^3.0.0-beta.7`, but it doesn't seem 100% yet(?)

I set up a [CodeSandbox project](https://codesandbox.io/p/sandbox/practical-butterfly-n8t5vy?file=%2Fsrc%2Fmiddleware.ts%3A11%2C1) which currently breaks with a client-side error on navigating to the intercepted route. Interestingly, when I integrated this sandbox with a private Git repository (which created a new sandbox project), it ran exactly as intended straight away - without any code changes.

Running the code locally, I got the same client-side error for a short while. I tried deleting the `.next` folder and `node_modules` folders, which didn't change anything, but suddenly everything started working without anything being changed... Even `next build` succeeds and the route interceptions work perfectly.

One thing that may be worth noting is that CodeSandbox doesn't seem to autoformat files in the `(.)login` directory, so it's possible that it's messing something up internally? I've not used CodeSandbox much before so it's possible there are some oddities I'm unfamiliar with.

**Comment by ClementDreptin** [comment]
I'm also facing issues when dealing with intercepted routes, I managed to reproduce the bug in a modified version of [nextgram](https://github.com/vercel-labs/nextgram) (the demo app vercel made to showcase intercepted routes).

I created a copy of nextgram and simply set up next-intl for it, it's available here:
https://github.com/ClementDreptin/next-intl-intercepted-routes

I also tried to remove the next-intl middleware and simulated its behavior by explicitely adding the locale in the each link, it's available in the [`next-intl-simulated` branch](https://github.com/ClementDreptin/next-intl-intercepted-routes/tree/next-intl-simulated).

I don't have the errors described above by @ReesMorris but sometimes the modal doesn't open. If I click on the first photo, it opens in a modal, but if I close this modal and try to open another photo, it goes the dedicated page instead of opening the modal (if I click on the first photo again, the modal opens as expected).

I suspect a problem in the middleware config matcher because the name of the route contains a dot (`(.)photos`). I tried to add another matcher that matches with the route but everything broke and I kept getting a `ChunkLoadError` when loading the home page. You can see this problem in the [`intercepted-routes-matcher` branch](https://github.com/ClementDreptin/next-intl-intercepted-routes/tree/intercepted-routes-matcher).

It's hard to tell if the problem comes from next-intl or next itself.

I hope this mimimal example will help us find a solution.

**Comment by ericmatthys** [comment]
I've integrated `next-intl` with the Nextgram example using the latest `next-intl` release candidate and Next.js 13.5.6.

https://github.com/ericmatthys/nextgram-intl

Using the new default `localePrefix: 'always'`, everything seems to work as expected. Switching that to `as-needed` will cause the photo routes to break so navigating to a photo leads to a 404 error.

https://github.com/ericmatthys/nextgram-intl/tree/minimal takes `next-intl` out entirely and just has a basic rewrite in middleware to prepend a static locale. The first time you navigate to a photo from the home page it'll work, but if you close the modal and try to navigate to another photo, nothing happens.

**Comment by ericmatthys** [comment]
https://github.com/ericmatthys/nextgram-intl/tree/minimal actually works ok when deployed to Vercel or when using the `build` / `start`. It's only with the dev server that the problematic behavior happens.

**Comment by ericmatthys** [comment]
Not much. I've pointed them to these existing GHIs so they are aware of them: https://github.com/vercel/next.js/issues?q=is:issue+is:open+rewrite+intercepting+route. No timeline on a fix though.

**Comment by jasperhartong** [comment]
Somehow direct navigation started working for me once I added `/[locale]/error.tsx` (see [Nextjs error handling docs](https://nextjs.org/docs/app/building-your-application/routing/error-handling#recovering-from-errors)). 

The console still logs an error with `Failed to load resource: the server responded with a status of 404 (Not Found)`, but it does continue and render the page (and the modal).

Perhaps this helps someone else :)

**Comment by ericmatthys** [comment]
https://github.com/vercel/next.js/issues/54147#issuecomment-1836864770

It seems this has been fixed, at least in my minimal reproduction.

**Comment by gorangatuzo** [comment]
Works for me with 14.0.4 now as well 👍

**Comment by hqw567** [comment]
我在next14.0.4版本中与next-intl3.4.1版本，使用拦截路由依然不起作用，我发现在开发环境中拦截路由起作用，在生产环境中就不起作用了。

**Comment by hqw567** [comment]
I used interception routing in next14.0.4 and next-intl3.4.1, but it still doesn't work. I found that interception routing works in the development environment, but it doesn't work in the production environment.

**Comment by hqw567** [comment]
> 埃

I found that intercepting routing is effective in the development environment, but it does not work in the production environment (`next build`)

**Comment by hqw567** [comment]
I guess that's why I used the `[locale]` folder

**Comment by hqw567** [comment]
Intercepting routes functions properly in Next.js version 14.0.5-canary.39 when used in conjunction with next-intl. If you are using this setup with Parallel Routes, please ensure that a `default.tsx` file is present in the Parallel Routes directory.

**Comment by nkorgik** [comment]
Still same issue for Next.js 14.2.4...

**Comment by vasilevach** [comment]
Hi there, I want to reconfirm that the issue only persists with next-intl. 

1. I tested the parallel routes without being in the [locale] folder: they work.
2. My second test was using dynamic route, that is not connected with the next-intl with parallel routes: again they work
3. Third test: parallel routes in [locale]: they stopped working with the error: TypeError: Cannot read properties of undefined (reading 'clientModules')

Environment:
"next": "^15.0.3",
"next-intl": "3.25.1",

Parallel route folder structure: 
<img width="194" alt="image" src="https://github.com/user-attachments/assets/2978cd04-65a2-4399-aff9-f35f35eaccdf" />

Middleware:

`import { NextRequest, NextResponse } from 'next/server';
import { getToken } from 'next-auth/jwt';
import { NextRequestWithAuth, withAuth } from 'next-auth/middleware';
import createIntlMiddleware from 'next-intl/middleware';

import { PAGES_DEFINITIONS } from '@/enum/pages';
import { hasPermissions } from '@/utils/navigation';

import { routing } from './i18n/routing';

const intlMiddleware = createIntlMiddleware(routing);

const authMiddleware = withAuth(
  async (req: NextRequestWithAuth) => {
    const response = NextResponse.next();
    const isAnAuthPage = req.nextUrl.pathname.startsWith('/auth');
    const isAnTestPage = req.nextUrl.pathname.startsWith('/test');


    if (isAnAuthPage || isAnTestPage) {
      // used to test my above statements
      return response;
    }

    return intlMiddleware(req);
  },
  {
    pages: {
      signIn: '/auth/signin',
      error: '/auth/error',
      signOut: '/auth/signout',
    },
  },
);

export default function middleware(req: NextRequest) {
  return (authMiddleware as any)(req);
}

export const config = {
  matcher: ['/((?!api|_next|.*\\..*).*)', '/(bg|en)/:path*'],
};
`

**Comment by hjhjdev** [comment]
I have same error @vasilevach said above.
TypeError: Cannot read properties of undefined (reading 'clientModules')
TypeError: Cannot read properties of undefined (reading 'entryCSSFiles')

**Comment by hjhjdev** [comment]
I found it works if i remove catch-all routes directory - [locale]/[...rest]

**Comment by vasilevach** [comment]
@hjhjdev thank you for pointing me in the right direction. My case was, that I had a [locale][...not-found] page that I also had to remove in order for the app to work. Having this catch-404-route obviously obscured the 404 error that I would have had initially for a missing default/page.tsx in some of the parallel routes structure. In my case it was in the root of the parallel routes folder. Anywho, I consider this error highly convoluted and I would cordially ask to replace it with something that might point people in the right direction.

**Comment by issam-seghir** [comment]
I have the same issue; the intercepted route isn't working in production. When I click the button to open the dialog, it goes directly to the page instead of opening the dialog. However, it works in development.

**Comment by NoelBank** [comment]
Any Updates here?

**Comment by davemecha** [comment]
I also had the issue, with a crashing app due to failing client rendered parallel routes in my production environment with a `ChunkLoadError`. In my case I deployed my app on Firebase App Hosting, which is based on Google Cloud Run.

I was able to workaround this issue with a rewrite in my `next.config.ts`.

``` ts
const nextConfig: NextConfig = {
  rewrites: async () => ({
    beforeFiles: [
      {
        source: '/_next/static/chunks/app/:folder*/@:slotName/:path*',
        destination: '/_next/static/chunks/app/:folder*/%40:slotName/:path*',
      },
    ],
    afterFiles: [],
    fallback: [],
  }),
};

const withNextIntl = createNextIntlPlugin();
export default withNextIntl(nextConfig);
```

This workaround should catch all slots, in case you have multiple slots.

I also created a repo to describe and reproduce the issue with a demo of the bug and the fix. https://github.com/davemecha/nextjs-parallel-routes-crash-mcve

My workaround is inspired by this discussion: https://github.com/vercel/next.js/discussions/73539 

I'm still not sure about why this bug happens when I run my prod environment in App Hosting but not when I run it locally with `npm run start` and why there are not more references about this major issue. I could imagine, some specific behavior of some prod environments might be related. Like this one... https://cloud.google.com/run/docs/known-issues#url-decode

**Comment by amannn** [comment]
I'm going to close this issue as it seems like the bugs that were described here were caused by Next.js and not `next-intl`. Personally, I've implemented parallel routes with a top-level `[locale]` segment and this worked fine for me. If you're still having issues, please ensure that you're on the latest Next.js version.
