### ISSUE TITLE
Unable to deploy on Netlify with latest packages

### ISSUE THREAD

**Issue by KrustyC** [amannn/next-intl#290]
### Description

I created a test Repo to report the problem. I am not sure whether this is dependant on `next-intl` or Netlify but I believe the new middleware created here certainly plays a role in this issue. 

When I run [this repo](https://github.com/KrustyC/next-netlify-test) locally with `netlify dev` all looks fine until I upgrade `@netlify/plugin-nextjs` to "4.36.1", at which point as soon as I run `netlify dev` I start getting an error "middleware is not a function" with the following stack trace 
```
TypeError: middleware is not a function
    at handler (file:///PATH/TO/REPO/repo/sites/next-netlify-test/.netlify/edge-functions/next-dev/index.js:78:28)
    at async FunctionChain.runFunction (https://64523ab4e7865600087fc3df--edge.netlify.app/bootstrap/function_chain.ts:390:22)
    at async FunctionChain.run (https://64523ab4e7865600087fc3df--edge.netlify.app/bootstrap/function_chain.ts:310:20)
    at async handleRequest (https://64523ab4e7865600087fc3df--edge.netlify.app/bootstrap/handler.ts:80:22)
    at async Server.#respond (https://deno.land/std@0.170.0/http/server.ts:299:18)
```

If I downgrade it seems to work just fine. As I said above I am not sure where the problem lies here, but I thought it may be useful to report it here for your awareness as I believe there may be quite a few people using this library and deploying their app on Netlify. If you want to test this out you can fork my repo and test it locally, following the README.

If you need anything else from me, please let me know.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/KrustyC/next-netlify-test

### Reproduction description

Steps to reproduce:
.1 Install the modules
2. Run `npm i @netlify/plugin-nextjs@latest next@latest`
3. Run `netlify dev`
4. Access http://localhost:8888 on your browser

### Expected behaviour

The page should load and the website should not break.

**Comment by amannn** [comment]
Hey @KrustyC, thanks for adding this report!

I haven't used Netlify for deployment yet and haven't seen this error so far. As far as I understand, the latest `@netlify/plugin-nextjs` version leads to the issue, with no changes to `next-intl`—right? That sounds like it might be a bug on the Netlify side then.

I saw you also added a bug report in the Netlify repo: https://github.com/netlify/next-runtime/issues/2106. I'll follow along there in case I can provide help from the `next-intl` side!

**Comment by KrustyC** [comment]
@amannn Brilliant! Thanks for the reply! Indeed this happens without any change to next-intl, the only reason I reported it here is that I am not sure if the middleware of next-intl could have anything to do with this issue they say in their limitations [here](https://github.com/netlify/next-runtime#limitations). 

I will of course keep following the issue I opened and test any new development as soon as possible, hoping to be helpful somehow

**Comment by amannn** [comment]
Sounds good! 🙌 

I just checked the Netlify limitations:

> Due to how the site configuration is handled when it's run using Netlify Edge Functions, data such as locale and defaultLocale will be missing on the req.nextUrl object when running netlify dev.
> However, this data is available on req.nextUrl in a production environment.

This should not affect routing with the App Router, `next-intl` doesn't rely on the mentioned properties on `nextUrl`.

**Comment by LekoArts** [comment]
Netlify employee here 👋 

We get the middleware from a named export here: https://github.com/netlify/next-runtime/blob/e1a1b5d779d1049007fc54143fd48f663156c38d/packages/runtime/src/templates/edge/next-dev.js#L39

We rely on this because the official Next.js docs tell users to use a named export:
- https://nextjs.org/docs/app/building-your-application/routing/middleware
- https://nextjs.org/docs/pages/building-your-application/routing/middleware

However, the next-intl docs tell users to use a default export: https://next-intl-docs.vercel.app/docs/next-13/middleware

@amannn This seems incorrect?

**Comment by amannn** [comment]
Hey @LekoArts, thanks for chiming in!

> We rely on this because the official Next.js docs tell users to use a named export:

That's interesting, I never noticed this. It seems like the Next.js docs are a bit inconsistent here, [in the advanced section they demonstrate a default export](https://nextjs.org/docs/app/building-your-application/routing/middleware#advanced-middleware-flags).

Auth.js is the most popular middleware for Next.js as far as I know and [they use a default export as well in their docs](https://authjs.dev/guides/basics/securing-pages-and-api-routes#nextjs-middleware) (also in [their advanced docs](https://next-auth.js.org/configuration/nextjs#advanced-usage)). What they do though, is [they export the middleware additionally as a named export](https://github.com/nextauthjs/next-auth/blob/f62c016725bf65e80a3cf5b6c59293120492fc4e/packages/next-auth/src/next/middleware.ts#L189-L210).

Seems a bit unfortunate that there's no clear API here from Next.js.

I think I'll add a named property to the middleware, so it works by default in the current Netlify runtime. Maybe you still want to consider a default export, since this seems to be popular?

**Comment by amannn** [comment]
@KrustyC I've just published `2.14.3-alpha.1` (non-RSC version) which should fix this. Can you maybe confirm that it does? I'll also publish an RSC beta on top of that afterward, once this is in `main`.

**Comment by LekoArts** [comment]
Thanks for collecting that information!

> The Middleware "pages/src/middleware" must export a `middleware` or a `default` function

I don't like it but if that's how things are then I'll also add code to our handling to handle both default and named export

**Comment by KrustyC** [comment]
@amannn I tried to test your fix by installing version  `2.14.3-alpha.1` but as soon as I ran `netlify dev` I started getting the following issue
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin' is not defined by "exports" in /Users/davidecrestini/repo/sites/thescrapbookers.blog/node_modules/next-intl/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at mod._resolveFilename (/Users/davidecrestini/repo/sites/thescrapbookers.blog/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18) {
  type: 'Error',
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I then upgraded back to `2.15.0-beta.3` and the error disappeared, although I am of course still getting the missing middleware function issue

**Comment by amannn** [comment]
Yes, as mentioned it's a non-RSC version that's based on the latest stable release. So for your demo you'd either have to disable/remove the RSC features, or use an example like [example-next-13 from the main branch](https://github.com/amannn/next-intl/tree/main/examples/example-next-13) which doesn't use RSC features yet.

I don't have experience with deploying to Netlify, that's why I hoped you could help to confirm the fix!

**Comment by KrustyC** [comment]
I see, I can try to modify my repo to avoid the usage of RSC and make sure it all works 😉

**Comment by KrustyC** [comment]
@amannn I tried to get rid of RSC components and implement a repo similar to the one you suggest, but unfortunately when I run `netlify dev` I keep on getting the middleware issue. 

If you want to reproduce it on your local, I think you should be able to give it a go using this repo: https://github.com/KrustyC/next-netlify-test

All you have to do is to run:
- `npm i -g netlify-cli`
- pull the repo, run `npm install` and `netlify dev`


I even tried different version of Next going down to 13.3.0, or using 13.4.2 and both give me the same error.

**Comment by KrustyC** [comment]
@amannn I tried to get rid of RSC components and implement a repo similar to the one you suggest, but unfortunately when I run netlify dev I keep on getting the middleware issue.

If you want to reproduce it on your local, I think you should be able to give it a go using this repo: https://github.com/KrustyC/next-netlify-test

All you have to do is to run:

- `npm i -g netlify-cli`
- pull the repo, run `npm install` and `netlify dev`

I even tried different versions of Next going down to 13.3.0, or using 13.4.2 and both give me the same error.

**Comment by KrustyC** [comment]
I have also tried to push to Netlify and although I had to make a couple of updates (like updating to Node 18), when I build the project I keep on getting  
```
TypeError: e.createContext is not a function
4:01:58 PM:     at 5076 (/opt/build/repo/.next/server/chunks/426.js:22382:11)
4:01:58 PM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:25:42)
4:01:58 PM:     at 1799 (/opt/build/repo/.next/server/chunks/426.js:16326:35)
4:01:58 PM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:25:42)
4:01:58 PM:     at 3130 (/opt/build/repo/.next/server/chunks/637.js:44:72)
4:01:58 PM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:25:42)
4:01:58 PM:     at 935 (/opt/build/repo/.next/server/app/[locale]/about-us/page.js:554:75)
4:01:58 PM:     at Function.__webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:25:42)
4:01:58 PM:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
4:01:58 PM:     at async collectGenerateParams (/opt/build/repo/node_modules/next/dist/build/utils.js:822:17)
4:01:58 PM: > Build error occurred
```

Which i never got before

**Comment by amannn** [comment]
@KrustyC I'm currently trying to run your example and I think there are a few more issues. I'll keep you posted!

**Comment by KrustyC** [comment]
Ok, thanks! Just FYI I realized that I pushed an incomplete version, so if you have not yet made any modification, it may be worth pulling the latest version 😉

**Comment by amannn** [comment]
Ok, so in regard to the original topic: It seems like we can't fix this in the `next-intl` middleware, because a property that we add doesn't end up in the netlify runtime.

If I add logging [for the middleware import in the netlify runtime](https://github.com/netlify/next-runtime/blob/e1a1b5d779d1049007fc54143fd48f663156c38d/packages/runtime/src/templates/edge/next-dev.js#LL38C1-L38C1), I see that everything is hidden behind the `default` property:

```
[next-dev] [Module: null prototype] {
  config: { matcher: [ "/((?!api|_next|.*\\..*).*)" ] },
  default: <ref *1> [Function: middleware] { middleware: [Circular *1] }
}
```

So currently, this can only be fixed in userland by adapting your `middleware.ts` as follows:

```tsx
import createMiddleware from "next-intl/middleware";

export const middleware = createMiddleware({
  locales: ["en", "it"],
  defaultLocale: "en",
});
```

Is this a known issue for middlewares like Auth.js too since they suggest a default export? So getting the middleware handling in Netlify in line with Next.js (handling both a default as well as a named export) is probably the right call here.

What worries me much more is that the `matcher` seems to be ignored by Netlify.

@KrustyC has configured it to ignore all static assets and only run on content routes: `/((?!icons|_next/static|_next/image|sitemap.xml|favicon.ico).*)`.

However when running `netlify dev` locally, I see that static assets are passed to the middleware nontheless, where the `next-intl` middleware creates invalid rewrites.

<img width="1904" alt="Screenshot 2023-05-16 at 11 41 04" src="https://github.com/amannn/next-intl/assets/4038316/ba00e9fa-dc49-41b1-a73c-6928103850ab">

Example URL: `/_next/static/media/376dd8dc38524313-s.p.woff2`

Typically we recommend to ignore all pathnames that are static, from the `api` folder or have an extension (`'/((?!api|_next|.*\\..*).*)'`).

This doesn't work either and all requests are passed to the middleware. I also tried a simple matcher like `['/', '/it', '/en']`, but this doesn't work either.

Is this the case for you too @KrustyC or am I doing something wrong?

On top of this, the netlify runtime changes the Next.js server code in `node_modules` to break the app, even when running the Next.js dev server without netlify:

```
Patching /Users/jan/Projects/forks/next-netlify-test/node_modules/next/dist/server/base-server.js
Done
Patching /Users/jan/Projects/forks/next-netlify-test/node_modules/next/dist/server/next-server.js
Done
```

Therefore if you run the app via `npm run dev` afterward, you can't access the app at http://localhost:3000/ anymore, where a rewrite to `/en` should be returned.

@KrustyC In regard to the bug with context you were seeing, this is because you were missing `'use client'` in many files. But if the Netlify issues are resolved, you should be able to continue using the RSC beta, so you don't need to refactor this.

For a reproduction, you can:
1. Check out https://github.com/amannn/next-netlify-test (contains a middleware fix as well as the conversion to client components)
2. `npm install`
3. Run `npm run dev`
4. The app works correctly, e.g. try to access `/`
5. `npm i -g netlify-cli`
6. `netlify dev`
7. The issues mentioned above appear
8. Run `npm run dev` again
9. The app is no longer accessible on `/`

I'm not sure if I'm doing something entirely wrong, but the netlify runtime seems quite unreliable to me here.

**Comment by KrustyC** [comment]
@amannn thanks for taking the time to look into this! 

With regard to the matcher I have never met such an issue before, and I am actually pretty sure it works fine on Netlify because yesterday I noticed that once I deployed my repo to Netlify and enabled Edge Functions, it was not processing images, as all images URL where prefixed by a `/_ipx` which I initially did not put into the `matcher`. As soon as I added such a path to my matcher it started working just fine. 

I tried your repo and to me, it looks as if it is properly configured for Netlify, so I am really not sure why matcher does not seem to work properly. As I said when I use the exact same matcher with [this repo](https://github.com/KrustyC/thescrapbookers.blog) everything works just fine and static assets are not passed to the `next-intl` middleware, although I can not run such repo locally at the moment, due to the middleware issue, but it works fine when deployed on Netlify at https://thescrapbookers.blog

**Comment by amannn** [comment]
Ok thanks, must be an issue on my end then.

Were you able to resolve your bug with the adapted middleware code mentioned above? If so, I'd close this issue.

**Comment by KrustyC** [comment]
After responding here I went on and tried your solution into my own repo and I found that actually once I change my middleware code to
```
const intlMiddleware = createMiddleware({
  locales: ["en", "it"],
  defaultLocale: "en",
});

export function middleware(req: NextRequest) {
  console.log("middleware processing " + req.nextUrl.href);
  return intlMiddleware(req);
}
```

I immediately start to get the same issues as you do with the middleware being executed on every path, even those that are meant to be excluded. @LekoArts could this be a potential issue with the way Netlify deals with the middleware?

**Comment by amannn** [comment]
You can btw. work around the Netlify issue by manually matching your pathname in the middleware:

```tsx
import createMiddleware from "next-intl/middleware";
import { NextRequest } from "next/server";

const intlMiddleware = createMiddleware({
  locales: ["en", "it"],
  defaultLocale: "en",
});

export function middleware(req: NextRequest) {
  if (new RegExp(config.matcher[0]).test(req.nextUrl.href)) {
    return intlMiddleware(req);
  }
}

export const config = {
  // Skip all paths that should not be internationalized
  matcher: ['/((?!api|_next|.*\\..*).*)']
};
```

I'll close this issue, since I think `next-intl` can't really do something here.

**Comment by KrustyC** [comment]
I have found a potential workaround which seems to work atm, although it is no ideal, but I am essentially doing the check from the matcher within the custom middleware, so my file looks as follow
```js
import createMiddleware from "next-intl/middleware";
import { NextRequest, NextResponse } from "next/server";

// export default createMiddleware({
//   locales: ["en", "it"],

//   // If this locale is matched, pathnames work without a prefix (e.g. `/about`)
//   defaultLocale: "en",
// });

const intlMiddleware = createMiddleware({
  locales: ["en", "it"],
  defaultLocale: "en",
});

const SKIP_PREFIXES = [
  "/_next",
  "/api",
  "/en/api",
  "/it/api",
  "/favicon.ico",
  "/robots.txt",
  "/_ipx",
  "/__nextjs",
  "/icons",
];

export function middleware(req: NextRequest) {
  if (SKIP_PREFIXES.some((prefix) => req.nextUrl.pathname.startsWith(prefix))) {
    return NextResponse.next();
  }

  console.log("middleware processing " + req.nextUrl.href);
  return intlMiddleware(req);
}

export default intlMiddleware;

export const config = {
  // Skip all paths that should not be internationalized
  matcher:
    "/((?!icons|_next/static|_next/image|sitemap.xml|robots.txt|_ipx|favicon.ico|api|en/api|it/api).*)",
};
```

This works on my local (although only one of my two fonts seems to be properly loading), but it is definitely not ideal

**Comment by KrustyC** [comment]
oh I just seen your response 😅 so I guess we basically got to the same solution although with a slightly different code. ANyway I believe it is ok to close the issue
