### ISSUE TITLE
With LocalePrefix: 'never' locale switches to previous choice on navigating app pages 

### ISSUE THREAD

**Issue by elensky** [amannn/next-intl#786]
### Description

While I used `LocalePrefix: 'never'` configuration I faced strange behaviour - if I navigate to any page of my app then change locale I see that locale was changed to previous choice when I navigate to other pages. I created CodeSandbox example of the issue, but looks like `LocalePrefix: 'never'` is not working there (I added a link to show this), you can download sources to run it locally.
Addition to this issue (it might be helpful): If I change locale several times on the third time it stops changing `NEXT_LOCALE` cookie value, but it works well only with `LocalePrefix: 'always'`

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-r7cscn

### Reproduction description

Steps to reproduce:
1. Open [link](https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-r7cscn) and download sources
2. Install dependencies (npm install) and run dev server (npm run dev)
3. Open http://localhost:3000/ in browser - it opens `/home` page
4. Click on the `Page` link - it opens '/page' page
5. Click `Switch to German` link
6. Click on the 'Home' link - page should be in German
7. Click on the `Page` link - there are two unexpected results: page will be in English or application crashes with text on the screen: `Application error: a client-side exception has occurred` and in console there is this log:
```
Warning: Cannot update a component (`HotReload`) while rendering a different component (`Router`). To locate the bad setState() call inside `Router`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
...
Uncaught Error: SEGMENT MISMATCH
...
The above error occurred in the <Router> component:
...
```

### Expected behaviour

Locale and translations should stay in German

**Comment by amannn** [comment]
Btw. in the lockfile of your repro is a slightly outdated version of next-intl. I couldn’t reproduce the issue after updating, but maybe you want to upgrade nonetheless in case your app is on an older version currently.

![IMG_9249](https://github.com/amannn/next-intl/assets/4038316/758053e5-cd4b-4369-b18e-6b9b609d9038)

**Comment by elensky** [comment]
Looks like you are doing the same, but for me it reproduces every time.

https://github.com/amannn/next-intl/assets/8483591/293880d3-ec68-472b-9acd-f4109bdcc045

I've tried to use different versions and firstly face this behaviour with latest version, I experimented that why maybe it has old version in package lock. My idea was that it can work on old version because when I run it with version 3.0.1 first time it seems worked as on your video, but after I tried find a version it start working so on all the version I've tried including 3.0.1.

I even tried to use different node version and next version. Issue is still there.

**Comment by elensky** [comment]
My local package-lock:
<img width="270" alt="Screenshot 2024-01-18 at 10 41 39" src="https://github.com/amannn/next-intl/assets/8483591/265811ed-4898-4190-afd0-b47e86d206a2">

**Comment by amannn** [comment]
I made some progress in regard to this in https://github.com/amannn/next-intl/pull/790. After hitting a blocker, I wanted to submit a bug report to Next.js, but found that the latest canary version of Next.js seems to improve the story here.

You can see my reproduction here: https://github.com/amannn/nextjs-bug-router-cache. After upgrading to the latest canary the buggy behavior was gone.

I think we should wait for the next stable release of Next.js and then continue looking into this.

Thanks again for the report!

**Comment by amannn** [comment]
So it turns out just a few hours after my comment Next.js 14.1 was released—which seems to fix the issue :).

https://github.com/amannn/next-intl/pull/790 furthermore includes a relevant fix for you. Updating both `next` and `next-intl` to the latest version should fix the error you were seeing!

**Comment by elensky** [comment]
Great thanks for your support and all work you are doing!
I've checked - version 14.1 solve the issue. I am happy. Haven't expected that it will be solved so fast.
Thanks again and good luck!

**Comment by bim-oulabi** [comment]
May I say that the issue of having wrong cookie under ```NEXT_LOCALE``` is still happening even after updating

for example if you visit '/en' the NEXT_LOCALE will be the previous one and so on

without having localePrefix sat to 'never'

**Comment by amannn** [comment]
@bim-oulabi Can you open a new issue with a reproduction?

**Comment by bim-oulabi** [comment]
I want to apologize as the issue was not because of next-intl,

To put it here in case anyone faced the issue in the future,

If you are using custom next/link to change locale

Disable prefetching by using ```prefetch={false}```

As prefetch will override the locale cookie with the new locale 

Or diasble default link behavior by using ```preventDefault()```

And navigate using hooks

**Comment by mxmzb** [comment]
Adding `prefetch={false}` to the links that change the locale fixed this for me (on latest Next.js 14 hosted on Vercel)

**Comment by beelzick** [comment]
Newest Next.js version 14.2.3 breaks it down again, downgraded to Next.js 14.1.4 (with next-inl 3.13.0) and it works

**Comment by amannn** [comment]
> Newest Next.js version 14.2.3 breaks it down again, downgraded to Next.js 14.1.4 (with next-inl 3.13.0) and it works

Seems like, there was a new report about this in https://github.com/amannn/next-intl/issues/1066. I'll reopen this for the time being until this is fixed on the Next.js side.

Does anyone know if there's an upstream bug report? If not, it might be a good idea to create one, maybe for the Next.js team to create a regression test.

**Comment by 3li7u** [comment]
> > Calling [router.refresh](https://nextjs.org/docs/app/api-reference/functions/use-router) will invalidate the Router Cache and make a new request to the server for the current route.

Calling `router.refresh(); ` after changing the locale solves the problem for me.
```ts
const handleLocaleChange = (locale: string) => {
    startTransition(() => {
      router.replace(`${pathname}?${searchParams.toString()}`, { locale });
      router.refresh(); // clear caching to make sure the locale cookie is set correctly
    });
  };
```

**Comment by mxmzb** [comment]
Seems to be broken again, and adding `prefetch={false}` does not help any more.

**Comment by ksin** [comment]
Same issue here with `prefetch={false}` as well.

**Comment by danieljpgo** [comment]
I'll try other solutions, but I wouldn't want to remove prefetch, as it helps to have faster navigation between pages.

**Comment by AhmedBaset** [comment]
This is still an issue even with
```js
experimental: {
    staleTimes: {
      static: 0,
      dynamic: 0,
    },
}
```
None of the mentioned workarounds worked.

**Comment by valentinilas** [comment]
For me the issue was that i was importing the Link element from next/link instead of doing it from the custom next-intl one:
```
// import Link from "next/link";
import { Link } from "@/i18n/routing";
```

**Comment by wadehammes** [comment]
Experiencing this as well with `as-needed`. Any time I need to test the page in Spanish, for example, any time I remove `/es` it still renders `/es` because the cookie `NEXT_LOCALE` remains `es`. Would love to have some sort of pre-routing check for the url locale to be set before just jumping to the cookie. We need automatic language detection so cant use the `localeCookie: false` solution.

**Comment by RobertChaw** [comment]
@wadehammes @gadcam 
I found a temporary workaround that doesn’t require turning off automatic language detection while still using "as-needed".

````ts
"use client";

import { Icon } from "@iconify/react";
import { languages } from "@/i18n/languages";
import { usePathname } from "@/i18n/routing";
import { useRouter } from "next/navigation";
import { useLocale } from "next-intl";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useSearchParams } from "next/navigation";

export function LanguageSelector() {
  const currentLocale = useLocale();
  const router = useRouter(); // 1. use useRouter from "next/navigation" instead of useRouter from @/i18n/routing to avoid error
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const handleSelectionChange = (newLocale: string) => {
    router.push(`/${newLocale}${pathname}?${searchParams.toString()}`); // 2. manually push the new locale to the url
  };

  return (
    <Select defaultValue={currentLocale} onValueChange={handleSelectionChange}>
      <SelectTrigger className="w-[180px]">
        <SelectValue>
          <div className="flex items-center gap-2">
            <Icon
              icon={
                languages.find((l) => l.code === currentLocale)?.icon ||
                "flag:gb-4x3"
              }
              className="w-4 h-4"
            />
            <span>
              {languages.find((l) => l.code === currentLocale)?.name ||
                "English"}
            </span>
          </div>
        </SelectValue>
      </SelectTrigger>
      <SelectContent>
        {languages.map((lang) => (
          <SelectItem key={lang.code} value={lang.code}>
            <div className="flex items-center gap-2">
              <Icon icon={lang.icon} className="w-4 h-4" />
              <span>{lang.name}</span>
            </div>
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}
